"""empty message

Revision ID: 12ac55d9de47
Revises: cfa02231b685
Create Date: 2025-12-07 16:50:13.657790

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '12ac55d9de47'
down_revision: Union[str, Sequence[str], None] = 'cfa02231b685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
