"""empty message

Revision ID: 554766fe59d9
Revises: 81fafec580d5
Create Date: 2025-12-09 21:38:32.448980

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '554766fe59d9'
down_revision: Union[str, Sequence[str], None] = '81fafec580d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
