"""empty message

Revision ID: 7d1165cbac48
Revises: b54c014abc37
Create Date: 2025-12-10 20:34:54.706008

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7d1165cbac48'
down_revision: Union[str, Sequence[str], None] = 'b54c014abc37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'payments',
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('stripe_payment_intent', sa.String(length=255), nullable=True),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=10), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('succeeded', sa.Boolean(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    )
    op.create_index(
        op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False
    )
    op.create_index(
        op.f('ix_payments_stripe_payment_intent'),
        'payments',
        ['stripe_payment_intent'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_stripe_payment_intent'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
