"""something

Revision ID: 81fafec580d5
Revises: 3d224d0e6065
Create Date: 2025-12-08 13:04:04.688986

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '81fafec580d5'
down_revision: Union[str, Sequence[str], None] = '3d224d0e6065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
