"""empty message

Revision ID: b45bb76fe66f
Revises: f695b3212ad1
Create Date: 2025-12-10 15:09:11.443382

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'b45bb76fe66f'
down_revision: Union[str, Sequence[str], None] = 'f695b3212ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
