"""empty message

Revision ID: b54c014abc37
Revises: fa76375f9b46
Create Date: 2025-12-10 15:16:16.190210

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'b54c014abc37'
down_revision: Union[str, Sequence[str], None] = 'fa76375f9b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
