"""empty message

Revision ID: f695b3212ad1
Revises: 73312084d53e
Create Date: 2025-12-10 14:13:26.493142

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f695b3212ad1'
down_revision: Union[str, Sequence[str], None] = '73312084d53e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'couriers', sa.Column('fullname', sa.String(length=120), nullable=False)
    )
    op.add_column('couriers', sa.Column('phone', sa.String(length=25), nullable=False))
    op.add_column(
        'couriers',
        sa.Column(
            'status',
            sa.Enum('active', 'offline', 'busy', name='courierstatus'),
            nullable=False,
        ),
    )
    op.add_column('couriers', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column(
        'delivery_addresses',
        sa.Column('fullname', sa.String(length=120), nullable=False),
    )
    op.add_column(
        'delivery_addresses', sa.Column('phone', sa.String(length=25), nullable=False)
    )
    op.add_column(
        'delivery_addresses', sa.Column('zip_code', sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_addresses', 'zip_code')
    op.drop_column('delivery_addresses', 'phone')
    op.drop_column('delivery_addresses', 'fullname')
    op.drop_column('couriers', 'is_verified')
    op.drop_column('couriers', 'status')
    op.drop_column('couriers', 'phone')
    op.drop_column('couriers', 'fullname')
    # ### end Alembic commands ###
