"""empty message

Revision ID: fa76375f9b46
Revises: b45bb76fe66f
Create Date: 2025-12-10 15:14:03.971506

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'fa76375f9b46'
down_revision: Union[str, Sequence[str], None] = 'b45bb76fe66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
