#!/bin/bash
set -e
set -o pipefail
set -o nounset

postgres_ready() {
python << END
import sys, psycopg2
try:
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${POSTGRES_HOST}",
        port="${POSTGRES_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}

echo "Waiting for PostgreSQL..."
until postgres_ready; do
  sleep 1
done
echo "PostgreSQL is UP."

exec "$@"
